### ISSUE TITLE
Broken url on pkgs.racket-lang.org

### ISSUE THREAD

**Issue by samth** [bartbes/mosquitto-racket#1]
The source url on pkgs.racket-lang.org for this package (and for `mosquitto-ffi`) is broken. Currently it is `git://github.com/‹user›/‹repo›` which is the default, but it should be `git://github.com/bartbes/mosquitto-racket`. This means that people can't install your package using the server.

**Comment by bartbes** [comment]
Considering I can't remember uploading it, I'm surprised to find it on there, especially twice.

**Comment by bartbes** [comment]
I've just updated the `mosquitto-ffi` package, and removed `libmosquitto`, though I am completely unsure of what to call the package. Hopefully this solves your issue?
